"""Sprint 0 Gate Review — aggregate spike results and emit decision report.

Run after S1-S6 spikes complete:
    uv run python sprint_0_spikes/gate_review.py > sprint_0_spikes/results/gate_review.md

Reads all spike result JSONs and produces a Markdown decision report aligned
with plan v1.0 §8 decision tree.
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

RESULTS = Path(__file__).parent / "results"

SPIKES = [
    ("S1", "TQuant-Lab + XTAI hello world", "s1_tquant_hello_world.json"),
    ("S2", "M1 plug into Zipline Algorithm", "s2_m1_plug_zipline.json"),
    ("S3", "FinLab bundle ingester POC", "s3_finlab_bundle_poc.json"),
    ("S3-verify", "Bundle readable via Zipline", "s3_verify_bundle.json"),
    ("S4", "Shioaji sandbox", "s4_shioaji_sandbox.json"),
    ("S5", "FinLab live polling", "s5_finlab_live_polling.json"),
    ("S6", "Streamlit + TimescaleDB", "s6_seed_equity_data.json"),  # opt
]

DECISION_TREE = {
    "all_pass": (
        "**進入 M2 Sprint 1**（plan v1.0 §6）。\n"
        "開始建 `core/` Protocol 層 + `adapters/data_bundle/finlab_bundle.py`。"
    ),
    "S1": "TQuant-Lab 不可用 → 退回 vectorbt-only 自建 adapter 路線（plan §8）",
    "S2": "M1 plug 失敗 → 修 plug code（不是路線問題，繼續 M2）",
    "S3": "FinLab bundle 失敗 → 暫用 FinMind bundle，M2 並行解決",
    "S4": "Shioaji 沙箱失敗 → M5 才需，暫不影響 M2-M4",
    "S5": "FinLab 即時資料失敗 → M4 才需，暫不影響 M2-M3",
    "S6": "Streamlit/TimescaleDB 失敗 → M3 才需，暫不影響 M2",
}


def load_results() -> dict:
    out = {}
    for spike_id, _, filename in SPIKES:
        path = RESULTS / filename
        if path.exists():
            try:
                out[spike_id] = json.loads(path.read_text(encoding="utf-8"))
            except Exception as e:
                out[spike_id] = {"passed": False, "error": f"load failed: {e}"}
        else:
            out[spike_id] = None
    return out


def emit_markdown(results: dict) -> str:
    lines = [
        "# Sprint 0 Gate Review",
        f"> 日期：{date.today().isoformat()}  |  總結 6 個 spike 結果並輸出 M2 啟動決策",
        "",
        "## 1. Spike 結果總表",
        "",
        "| Spike | 主題 | 結果 | 備註 |",
        "| :---: | :--- | :---: | :--- |",
    ]
    for spike_id, title, _ in SPIKES:
        r = results.get(spike_id)
        if r is None:
            status = "⏭️ 未跑"
            note = "未執行 / 無結果檔"
        elif r.get("passed"):
            status = "✅ PASS"
            note = "詳見結果 JSON"
        else:
            status = "❌ FAIL"
            err = r.get("error") or r.get("checks", {})
            note = f"{str(err)[:80]}..." if len(str(err)) > 80 else str(err)
        lines.append(f"| {spike_id} | {title} | {status} | {note} |")

    failed = [s for s, _, _ in SPIKES if results.get(s) and not results[s].get("passed")]
    passed = [s for s, _, _ in SPIKES if results.get(s) and results[s].get("passed")]
    not_run = [s for s, _, _ in SPIKES if results.get(s) is None]

    lines += [
        "",
        f"**合計**：{len(passed)} PASS / {len(failed)} FAIL / {len(not_run)} 未跑",
        "",
        "## 2. 決策",
        "",
    ]

    if not failed and not not_run:
        lines.append("### ✅ 全綠 — 進入 M2 Sprint 1")
        lines.append("")
        lines.append(DECISION_TREE["all_pass"])
    elif failed:
        lines.append("### ⚠️ 部分 FAIL — 按決策樹判斷")
        lines.append("")
        for spike_id in failed:
            spike_key = spike_id.split("-")[0]  # 'S3-verify' -> 'S3'
            action = DECISION_TREE.get(spike_key, "未定義")
            lines.append(f"- **{spike_id} FAIL**：{action}")
    else:
        lines.append("### ⏭️ 有未跑項目 — 補跑後再 review")
        lines.append("")
        for spike_id in not_run:
            lines.append(f"- **{spike_id} 未跑**")

    lines += [
        "",
        "## 3. 下一步",
        "",
        "若 S1+S2+S3 全綠 → 可立即進入 M2 Sprint 1 第一週工作項目（plan v1.0 §6）：",
        "- Day 1：寫 `core/data_provider.py` Protocol",
        "- Day 2-3：`adapters/data_bundle/finlab_bundle.py` + cache wrapper",
        "- Day 4-5：`strategies/four_layer_resonance/__init__.py` Zipline algorithm wrapper",
        "",
        "S4/S5/S6 即使 FAIL 也可延後（影響後續 milestone，但不影響 M2 啟動）。",
        "",
        "---",
        f"*Generated by `sprint_0_spikes/gate_review.py` on {date.today().isoformat()}*",
    ]
    return "\n".join(lines)


def main():
    results = load_results()
    md = emit_markdown(results)
    print(md)
    out_file = RESULTS / "gate_review.md"
    out_file.write_text(md, encoding="utf-8")
    # Also drop a summary to stderr-like marker
    import sys

    print(f"\n--- gate_review written to {out_file} ---", file=sys.stderr)


if __name__ == "__main__":
    main()
